### PR TITLE
Fix typo in variable name

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Fixed a typo in variable name `{firstname}`
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Related to https://github.com/PrestaShop/PrestaShop/issues/21296
| How to test?  | N/A

### CODE REVIEW

**Review by matks — APPROVED** [review]

**Comment by jolelievre** [comment]
This one is a duplicate of this PR https://github.com/PrestaShop/mjml-theme-converter/pull/7

I didn't see you already pushed the fix, however the #7 fixes another template and updates the dependencies to use PHP 7.3

**Comment by eternoendless** [comment]
Mine was first! :P

**Comment by jolelievre** [comment]
I don't mind merging your's first I'll rebase mine after ^^

**Review by jolelievre — APPROVED** [review]

**Comment by jolelievre** [comment]
Thank you @eternoendless

**Pull request merged**
